### PR TITLE
tests: refactored tests to use _by_lua_block directives exclusively.

### PR DESCRIPTION
**Pull request by thibaultcha**

### CODE REVIEW

**Comment by agentzh** [comment]
@thibaultcha Our policy here is to avoid touching existing test cases using the old `*_by_lua` directives. This is because to test the tests themselves we have to make them experience state changes (like from failing to passing or the other way around) and editing existing tests always risk breaking them (even though they are still passing but tests that are *always* passing are useless as well).

**Comment by thibaultcha** [comment]
@agentzh Is this a policy that only applies to this project? I have seen other libraries (lua-resty-core maybe, but not only?) migrating from the old `by_lua` to the new `by_lua_block` form iirc.

**Comment by agentzh** [comment]
@thibaultcha The policy applies to all repos under `openresty/`. Only new test cases or newly debugged test cases should switch to the new syntax.

**Comment by thibaultcha** [comment]
@agentzh Gotcha :+1:

FYI, there has been at least 2 occurrences that I know of of such updates under the oprenresty/ namespace: https://github.com/openresty/lua-resty-core/commit/729e1861282e1e4ae478825daa44950d7fecdae3 and https://github.com/openresty/lua-resty-lock/commit/596b34e82e627604b31d555250f88beb631d69f8.

**Comment by agentzh** [comment]
@thibaultcha Oh, that was my bad. I should have rejected them :)

**Comment by agentzh** [comment]
Sorry for the confusions.

**Comment by thibaultcha** [comment]
No problem! Sorry for the misleading contributions!

**Pull request closed without merging**
